### ISSUE TITLE
blink is a hidden implied feature not yet supported

### ISSUE THREAD

**Issue by silky** [andykitchen/hello#4]

**Comment by andykitchen** [comment]
I'm worried about how blink will interact with the newly introduced server feature.

**Comment by silky** [comment]
i think this might require a new http spec - https://http2.github.io/

**Comment by silky** [comment]
(we should implement this quickly, there seems to be a lot of demand; see #3)

**Comment by silky** [comment]
fixed in https://github.com/andykitchen/hello/commit/4aaf4d8b53a03c8b6ff126eae8fee9afc6c8297f
