### ISSUE TITLE
unicode issue

### ISSUE THREAD

**Issue by silky** [andykitchen/hello#5]
⚡ 02:42 PM noon ∈ hello@master>./hello -u                                                            1 ↵ ▲▲▲ 
./hello:61: invalid multibyte char (US-ASCII)
./hello:61: invalid multibyte char (US-ASCII)
./hello:61: syntax error, unexpected $end, expecting keyword_end
    line = "─" \* (greeting.length+2)

**Comment by andykitchen** [comment]
nice! This will really help people with non UTF-8 locales contribute.
